# Generated by Django 4.2.18 on 2025-03-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_faceencoding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackStudent',
            new_name='FeedBackParent',
        ),
        migrations.RenameField(
            model_name='feedbackparent',
            old_name='student_id',
            new_name='parent_id',
        ),
    ]
