# Generated by Django 4.2.18 on 2025-03-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_rename_feedbackstudent_feedbackparent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackParent',
            new_name='FeedBackParents',
        ),
    ]
