# Generated by Django 4.2.18 on 2025-03-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_rename_feedbackparent_feedbackparents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackparents',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.parents'),
        ),
    ]
