# Generated by Django 4.2.11 on 2025-03-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_feedbackparents_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default='0', max_length=1),
        ),
    ]
