# Generated by Django 4.2.11 on 2025-03-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_attendancereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
