# Generated by Django 4.2.11 on 2025-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_attendancechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
