# Generated by Django 5.2 on 2025-05-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_attendancereport_check_in_attendancereport_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
