# Generated by Django 5.2 on 2025-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_staffs_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
