from django.urls import path
from student_management_app import FaceRecognitionViews
from . import views
from .import HodViews, StaffViews, ParentViews, FaceRecognitionViews
from student_management_app.api.views import login_view, get_student_info, mark_attendance_api
from student_management_app import FaceRecognitionViews


urlpatterns = [
    path('parent_home/', ParentViews.parent_home, name="parent_home"),
    path('staff/create_dataset/<int:student_id>/', FaceRecognitionViews.create_dataset_view, name='create_dataset_view'),
    path('parent_all_notifications/', ParentViews.parent_all_notifications, name="parent_all_notifications"),
    path('parent_view_attendance/', ParentViews.parent_view_attendance, name="parent_view_attendance"),
    path('parent_profile/', ParentViews.parent_profile, name="parent_profile"),
    path('parent_apply_leave/', ParentViews.parent_apply_leave, name="parent_apply_leave"),
    path('parent_apply_leave_save/', ParentViews.parent_apply_leave_save, name="parent_apply_leave_save"),
    path('parent_feedback/', ParentViews.parent_feedback, name="parent_feedback"),
    path('parent_feedback_save/', ParentViews.parent_feedback_save, name="parent_feedback_save"),
    path('api/doLogin', views.api_login, name='api_login'),
    path('api/mark_attendance_api/', mark_attendance_api, name='mark_attendance_api'),
    path('api/mark_attendance_api', mark_attendance_api, name='mark_attendance_api_no_slash'),
    path('api/login/', login_view, name='login_view'),
    path('api/get_student_info/', get_student_info, name='get_student_info'),

    path('', views.loginPage, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_staff/', HodViews.add_staff, name="add_staff"),
    path('add_staff_save/', HodViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', HodViews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', HodViews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', HodViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', HodViews.delete_staff, name="delete_staff"),
    path('add_grade/', HodViews.add_grade, name="add_grade"),
    path('add_grade_save/', HodViews.add_grade_save, name="add_grade_save"),
    path('manage_grade/', HodViews.manage_grade, name="manage_grade"),
    path('edit_grade/<grade_id>/', HodViews.edit_grade, name="edit_grade"),
    path('edit_grade_save/', HodViews.edit_grade_save, name="edit_grade_save"),
    path('delete_grade/<grade_id>/', HodViews.delete_grade, name="delete_grade"),
    path('manage_academic_year/', HodViews.manage_academic_year, name="manage_academic_year"),
    path('add_academic_year/', HodViews.add_academic_year, name="add_academic_year"),
    path('add_academic_year_save/', HodViews.add_academic_year_save, name="add_academic_year_save"),
    path('edit_academic_year/<academic_year_id>/', HodViews.edit_academic_year, name="edit_academic_year"),
    path('edit_academic_year_save/', HodViews.edit_academic_year_save, name="edit_academic_year_save"),
    path('delete_academic_year/<academic_year_id>/', HodViews.delete_academic_year, name="delete_academic_year"),
    path('add_student/', HodViews.add_student, name="add_student"),
    path('add_student_save/', HodViews.add_student_save, name="add_student_save"),
    path('edit_student/<student_id>/', HodViews.edit_student, name="edit_student"),
    path('edit_student_save/', HodViews.edit_student_save, name="edit_student_save"),
    path('manage_student/', HodViews.manage_student, name="manage_student"),
    path('delete_student/<student_id>/', HodViews.delete_student, name="delete_student"),
    path('add_stream/', HodViews.add_stream, name="add_stream"),
    path('add_stream_save/', HodViews.add_stream_save, name="add_stream_save"),
    path('manage_stream/', HodViews.manage_stream, name="manage_stream"),
    path('edit_stream/<stream_id>/', HodViews.edit_stream, name="edit_stream"),
    path('edit_stream_save/', HodViews.edit_stream_save, name="edit_stream_save"),
    path('delete_stream/<stream_id>/', HodViews.delete_stream, name="delete_stream"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('parent_feedback_message/', HodViews.parent_feedback_message, name="parent_feedback_message"),
    path('parent_feedback_message_reply/', HodViews.parent_feedback_message_reply, name="parent_feedback_message_reply"),
    path('staff_feedback_message/', HodViews.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', HodViews.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('student_leave_view/', HodViews.student_leave_view, name="student_leave_view"),
    path('student_leave_approve/<leave_id>/', HodViews.student_leave_approve, name="student_leave_approve"),
    path('student_leave_reject/<leave_id>/', HodViews.student_leave_reject, name="student_leave_reject"),
    path('staff_leave_view/', HodViews.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', HodViews.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', HodViews.staff_leave_reject, name="staff_leave_reject"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_edit_attendance_list/', HodViews.admin_edit_attendance_list, name="admin_edit_attendance_list"),
    path('admin_get_attendance_dates/', HodViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student/', HodViews.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    path('add_parent/', HodViews.add_parent, name="add_parent"),
    path('add_parent_save/', HodViews.add_parent_save, name="add_parent_save"),
    path('manage_parent/', HodViews.manage_parent, name="manage_parent"),
    path('edit_parent/<int:parent_id>/', HodViews.edit_parent, name="edit_parent"),
    path('edit_parent_save/', HodViews.edit_parent_save, name="edit_parent_save"),
    path('delete_parent/<int:parent_id>/', HodViews.delete_parent, name="delete_parent"),
    path('generate_face_encodings', HodViews.generate_face_encodings_for_existing_students, name="generate_face_encodings"),
    path('export_students', HodViews.export_students, name="export_students"),
    path('export_all_students', HodViews.export_all_students, name="export_all_students"),
    path('bulk_face_enrollment', HodViews.bulk_face_enrollment, name="bulk_face_enrollment"),
    path('create_dataset_bulk', HodViews.create_dataset_bulk, name="create_dataset_bulk"),
    path('student_attendance_detail/<int:student_id>/', HodViews.student_attendance_detail, name="student_attendance_detail"),
    path('save_face_image', HodViews.save_face_image, name="save_face_image"),
    path('next_enrollment_student', HodViews.next_enrollment_student, name="next_enrollment_student"),
    path('generate_face_encodings', HodViews.generate_face_encodings, name="generate_face_encodings"),
    path('train_model', HodViews.train_model, name="train_model"),
    path('save_face_dataset', HodViews.save_face_dataset, name="save_face_dataset"),
    path('create_dataset/<int:student_id>/', HodViews.create_dataset, name="create_dataset"),
    path('get_attendance_records', HodViews.get_attendance_records, name='get_attendance_records'),
    path('get_streams_by_grade', HodViews.get_streams_by_grade, name='get_streams_by_grade'),
    path('get_attendance_details', HodViews.get_attendance_details, name='get_attendance_details'),
    path('get_admin_attendance', HodViews.get_admin_attendance, name='get_admin_attendance'),
    path('get_students_by_stream', HodViews.get_students_by_stream, name='get_students_by_stream'),
    path('admin_edit_attendance/<str:attendance_id>/', HodViews.admin_edit_attendance, name='admin_edit_attendance'),
    path('save_updated_attendance', HodViews.save_updated_attendance, name='save_updated_attendance'),
    path('check_username_exists/', views.check_username_exists, name='check_username_exists'),

    # URLS for Staff
    path('get_students', StaffViews.get_students, name='get_students'),
    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_detect_faces', StaffViews.staff_detect_faces, name="staff_detect_faces"),
    path('staff_recognize_face', StaffViews.staff_recognize_face, name="staff_recognize_face"),
    path('save_attendance_data/', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('staff_view_attendance/', StaffViews.staff_view_attendance, name="staff_view_attendance"),
    path('get_attendance_dates/', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', StaffViews.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data/', StaffViews.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', StaffViews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', StaffViews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', StaffViews.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile/', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_update/', StaffViews.staff_profile_update, name="staff_profile_update"),
    path('add_student_face_encoding', StaffViews.add_student_face_encoding, name='add_student_face_encoding'),
    path('staff_take_attendance_with_face', StaffViews.staff_take_attendance_with_face, name='staff_take_attendance_with_face'),
    path('staff_detect_faces', StaffViews.staff_detect_faces, name="staff_detect_faces"),
    path('staff_save_attendance_with_face', StaffViews.staff_save_attendance_with_face, name="staff_save_attendance_with_face"),
    path('staff/verify_fingerprint', StaffViews.verify_fingerprint, name="verify_fingerprint"),
    path('export_attendance_csv/', StaffViews.export_attendance_csv, name='export_attendance_csv'),

    # URLS for Student
    # path('student_home/', StudentViews.student_home, name="student_home"),
    # path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    # path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('check_new_notifications/', StaffViews.check_new_notifications, name='check_new_notifications'),
]
